import type { BackendOperationId } from "../../electron/desktop-port";

type ControlContract =
  | { kind: "desktop"; bridge: string }
  | { kind: "operation"; operations: BackendOperationId[] }
  | { kind: "unavailable"; reason: string }
  | { kind: "view"; behavior: string };

const view = (behavior: string): ControlContract => ({ kind: "view", behavior });
const operation = (...operations: BackendOperationId[]): ControlContract => ({ kind: "operation", operations });

export const controlContracts: Record<string, ControlContract[]> = {
  "项目": [view("route:/projects")],
  "当前工作流": [view("route:/projects/:projectId")],
  "Planner": [view("route:stage/planner")],
  "Designer": [view("route:stage/designer")],
  "Builder": [view("route:stage/builder")],
  "Reviewer": [view("route:stage/reviewer")],
  "Deployer": [view("route:stage/deployer")],
  "产出与交接": [view("route:artifacts")],
  "审批与能力": [view("route:approvals")],
  "冲突与恢复": [view("route:recovery")],
  "事件与诊断": [view("route:/diagnostics")],
  "设置": [view("route:/settings")],
  "通知": [view("route:/diagnostics")],
  "切换为深色模式": [view("theme:dark")],
  "切换为浅色模式": [view("theme:light")],
  "刷新": [view("repeat current queries")],
  "刷新列表": [operation("list_projects_api_v1_projects_get")],
  "重新检查": [operation("health_api_v1_health_get", "readiness_api_v1_readiness_get", "system_info_api_v1_system_info_get", "list_recoveries_api_v1_recovery_get")],
  "重试": [view("repeat failed query")],
  "返回项目": [view("route:/projects")],
  "项目主页": [view("route:/projects/:projectId")],
  "前往预检": [view("route:preflight")],
  "退出": [{ kind: "desktop", bridge: "requestWindowClose" }],
  "进入项目": [view("route:/projects")],
  "选择目录": [{ kind: "desktop", bridge: "selectDirectory" }],
  "创建并预检": [operation("create_project_api_v1_projects_post")],
  "打开": [operation("open_project_api_v1_projects__project_id__open_post")],
  "重新预检": [operation("run_preflight_api_v1_projects__project_id__preflight_post")],
  "创建并开始工作流": [operation("create_workflow_api_v1_projects__project_id__workflows_post", "start_workflow_api_v1_workflows__workflow_id__start_post")],
  "关闭项目": [operation("close_project_api_v1_projects__project_id__close_post")],
  "继续": [operation("control_workflow_api_v1_workflows__workflow_id___action__post")],
  "暂停": [operation("control_workflow_api_v1_workflows__workflow_id___action__post")],
  "停止": [operation("control_workflow_api_v1_workflows__workflow_id___action__post")],
  "放弃": [operation("control_workflow_api_v1_workflows__workflow_id___action__post", "resolve_recovery_api_v1_recovery__recovery_id___action__post")],
  "继续恢复": [operation("resolve_recovery_api_v1_recovery__recovery_id___action__post")],
  "更正此消息": [view("prepare immutable correction")],
  "发送": [operation("append_message_api_v1_rooms__room_id__messages_post")],
  "加入队列": [operation("enqueue_task_api_v1_rooms__room_id__tasks_post")],
  "开始": [operation("start_task_api_v1_tasks__task_id__start_post")],
  "取消": [operation("cancel_task_api_v1_tasks__task_id__cancel_post"), view("cancel local correction")],
  "开始讨论": [operation("transition_stage_api_v1_workflows__workflow_id__stages__stage__transition_post")],
  "进入产出": [operation("transition_stage_api_v1_workflows__workflow_id__stages__stage__transition_post")],
  "提交双校审查": [operation("transition_stage_api_v1_workflows__workflow_id__stages__stage__transition_post")],
  "开始返工": [operation("transition_stage_api_v1_workflows__workflow_id__stages__stage__transition_post")],
  "返回讨论": [operation("transition_stage_api_v1_workflows__workflow_id__stages__stage__transition_post")],
  "冲突处理后继续讨论": [operation("transition_stage_api_v1_workflows__workflow_id__stages__stage__transition_post")],
  "恢复讨论": [operation("transition_stage_api_v1_workflows__workflow_id__stages__stage__transition_post")],
  "重新打开": [operation("reopen_stage_api_v1_workflows__workflow_id__stages__stage__reopen_post")],
  "要求重写": [operation("decide_gate_approval_api_v1_approvals__approval_id__decision_post")],
  "批准": [operation("decide_gate_approval_api_v1_approvals__approval_id__decision_post", "decide_capability_api_v1_capability_requests__request_id__decision_post")],
  "拒绝": [operation("decide_capability_api_v1_capability_requests__request_id__decision_post")],
  "提交解决方案": [operation("resolve_conflict_api_v1_projects__project_id__conflicts__conflict_id__resolve_post")],
  "规划并恢复": [operation("plan_restore_api_v1_projects__project_id__checkpoints__checkpoint_id__restore_plan_post", "restore_checkpoint_api_v1_projects__project_id__checkpoints__checkpoint_id__restore_post")],
  "保存设置": [{ kind: "unavailable", reason: "SettingsQuery and settings write operation are absent" }],
  "创建模型配置": [operation("create_profile_api_v1_model_profiles_post")],
  "保存模型配置": [operation("update_profile_api_v1_model_profiles__profile_id__put")],
  "取消编辑": [view("discard local form edit")],
  "测试连接": [{ kind: "unavailable", reason: "ModelProfileTest operation is absent" }],
  "读取当前分配": [operation("get_room_assignment_api_v1_rooms__room_id__model_assignment_get")],
  "准备新分配": [view("prepare assignment form")],
  "保存 Room 分配": [operation("assign_room_models_api_v1_rooms__room_id__model_assignment_put")],
  "编辑": [view("load selected backend entity into a local form")],
  "刷新摘要": [operation("health_api_v1_health_get", "readiness_api_v1_readiness_get", "system_info_api_v1_system_info_get", "list_recoveries_api_v1_recovery_get")],
  "同步当前事件流": [{ kind: "desktop", bridge: "backend.requestReplay" }],
  "读取审计": [operation("replay_events_api_v1_events_replay_get", "list_tool_calls_api_v1_workflows__workflow_id__tool_calls_get")],
  "导出诊断包": [{ kind: "unavailable", reason: "DiagnosticsExport operation is absent" }],
};

export const dynamicControlLabels = [
  "Planner",
  "Designer",
  "Builder",
  "Reviewer",
  "Deployer",
  "开始讨论",
  "进入产出",
  "提交双校审查",
  "开始返工",
  "返回讨论",
  "冲突处理后继续讨论",
  "恢复讨论",
  "创建模型配置",
  "保存模型配置",
] as const;
